### PR TITLE
Overloads for operations on multiple layers

### PR DESCRIPTION
**Pull request by gabrieldansereau**
Following up on the idea of removing the need to interact with the `grid` field, I suggest some more overloads for functions applied to more than one layer. For example, functions would work directly with `layer1` & `layer2`, instead of `layer1.grid` & `layer2.grid`:
```
julia> layer1 = SimpleSDMResponse([1 2]); layer2 = SimpleSDMResponse([3 4]);
julia> layer1 + layer2
SimpleSDMResponse{Int64}(Union{Nothing, Int64}[4 6], -180.0, 180.0, -90.0, 90.0
```
I started working on this when we used `NaN` for missing values, so the fix was quite easy. It's more complicated with `nothing`, and I'm not always sure of the workarounds I've found, but I guess it makes it even more useful.

### To-do list
- [x] Overload for `extrema()`
- [x] Fix type returned by `broadcast`
- [x] `min()` & `max()`
- [x] `mean()` & `std()`
- [x] Extend `_layers_are_compatible()` for more than two layers
- [x] Math operators `+`, `-`, `*` , `/`
- [x] Add more tests for these new overloads?
- ~~Extend `broadcast!()`?~~
- ~~Examples in documentation?~~

### CODE REVIEW

**Comment by gabrieldansereau** [comment]
`broadcast()` and functions that relied on it, such as `abs()`, always returned the type `Any` for the layers instead of `Union{Nothing, Float32}`, breaking other functions like `maximum()`. I don't know if it was the desired result, but it seemed more like a bug and I didn't see any reason for it, so I fixed it in 6d3f2a517d1e98756c7ce68477d8242131831cfd.

```
julia> temperature = worldclim(1)
julia> maximum(temperature)
30.98764f0
julia> maximum(broadcast(abs, temperature))
ERROR: MethodError: no method matching iterate(::SimpleSDMPredictor{Any})
```

**Comment by tpoisot** [comment]
Good catch @gabrieldansereau, I've been meaning to fix this.

**Comment by gabrieldansereau** [comment]
@tpoisot I'm done with the features I wanted to add in this pull-request

**Comment by tpoisot** [comment]
I just updated it with the changes from #31 , will check that everything is :+1: and merge.

**Pull request merged**
